version: "3.8"

services:
  app-dev:
    image: ${VENTURE_DOCKERHUB_USERNAME}/venture-api:dev
    container_name: venture-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "1337:5000"
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
      REDIS_HOST: venture-redis-dev
      POSTGRES_HOST: venture-postgres-dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: yarn dev

  redis:
    container_name: venture-redis-dev
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1"]
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  postgres:
    container_name: venture-postgres-dev
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-venture}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-venture}
      POSTGRES_DB: ${POSTGRES_DB:-venture_dev}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-venture}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  redis_data_dev:
  postgres_data_dev:
