export const COMPANY_ROUTES = {
  createUser: "/create",
  deletedUser: "/delete/:id",
  getDownline: "/downline",
  getUsersByParentId: "/downline/hierarchy/:parentId",
  getMe: "/me/profile",
  toggleUserStatus: "/:id/toggle",
  changePassword: "/change-password",
  updateUserProfile: "/profile/update",
  getDownlineDashboard: "/downline/dashboard",
  getAdminDashboard: "/downline/admin/dashboard",
  getDistributorDashboard: "/downline/distributor/dashboard",
  getSubDistributorDashboard: "/downline/sub-distributor/dashboard",
  getStoreDashboard: "/downline/store/dashboard",
  exportDashboardData: "/downline/export",
  getDashboardUpdates: "/downline/updates",
  getUserDetailedStats: "/downline/stats/:targetUserId",
  getComparativeAnalysis: "/downline/compare",
};
