#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/sh
red='\033[0;31m'

if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "🔨❌ ${red} Aborting commit. Your commit message is invalid. Please use git commit -m "fix: commit_message" for better commits...🔨❌" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "🔨❌${red} Aborting commit. Your commit message is too long.🔨❌" >&2
    exit 1
fi